### ISSUE TITLE
Listing item title overflows

### ISSUE THREAD

**Issue by pgrandeg** [openeuropa/oe_paragraphs#118]
Hello team,

We realize that Listing item title for "Thumbnail primary" overflows behind their siblings. It could be solved adding word-break CSS, but this module is taking styles from oe_theme.
It's not happening to other types, "Highlight" for instance. Could you please check and solve it? Here is an example of the issue:
![image](https://user-images.githubusercontent.com/43410415/93888882-d981dc00-fce8-11ea-86a3-9fb2fb7a89d1.png)
https://europa.eu/europass/nl/europass-certificate-supplement

Thank you for your support,
Pablo

**Comment by pgrandeg** [comment]
Hello,
Any update on this? Thank you!
Pablo

**Comment by brummbar** [comment]
This is tied to the theming layer (maybe oe_theme). oe_paragraphs offers only paragraphs, without rendernig.
