### ISSUE TITLE
Listing item description is never shown for Highlight type

### ISSUE THREAD

**Issue by pgrandeg** [openeuropa/oe_paragraphs#119]
Hello team,

We realize that Listing item paragraph has a strange behaviour. From backoffice, this item is showing
- Link
- Title
- Description
- Image
- META

but description field is never shown in front-end. Could you please check and solve it?

Thank you for your support,
Pablo

**Comment by pgrandeg** [comment]
Hello,
Any update on this? Thank you!
Pablo

**Comment by brummbar** [comment]
Rendering of paragraphs is handled in oe_theme.
