### ISSUE TITLE
Paragraphed content demo -> add from library end-up in an infinitive loop (js code)

### ISSUE THREAD

**Issue by Elsa-E4-user** [openeuropa/oe_paragraphs#126]
- Installed oe_paragraph to a open europa template site in a local DEV env
- Enabled library and demo
- Tried to create a paragraph from Add from library -> noting happen and a warning is raised in the browser inviting to stop the page.

console contain this error: WTERROR:'cck' doesn't exist!
I followed the load.js script and cck library seems to be correctly added as cross-origin anonymous uploading, but then failed.

Screenshot attached
![openeropa-demo-issue](https://user-images.githubusercontent.com/34245289/112127992-41e14580-8bc6-11eb-80cf-a9b5403597cd.jpg)

**Comment by brummbar** [comment]
This is an error with webtools and not related to oe_paragraphs.
