### ISSUE TITLE
Cannot show additional fields on accordion paragraphs

### ISSUE THREAD

**Issue by pmichelazzo** [openeuropa/oe_paragraphs#137]
Hello fellows,

I'm using the accordion provided by the oe_paragraphs on the new Digital Strategy website (DG-Connect). The module is working fine but I'm trying to add a new field inside the accordion to display a title to the accordions but, unfortunately, I can't display the data on the page.

Somebody have any documentation about how to add a field disaplay the content or is this a bug?

Thanks a lot.

**Comment by jazio** [comment]
@pmichelazzo what you are trying to achieve can be done via a custom block, I'll create an OES ticket and show you how.

**Comment by pmichelazzo** [comment]
Hello @jazio 
Thanks a lot for the help.

Best

**Comment by jazio** [comment]
@pmichelazzo  here is a proposal for your solution: https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OES-500

**Comment by brummbar** [comment]
Closing as oe_paragraphs doesn't handle the rendering, just the fields.
