### ISSUE TITLE
Drush commands not available using Drush 12

### ISSUE THREAD

**Issue by dxvargas** [openeuropa/oe_paragraphs#217]
The drush commands introduced in #197 and #206 are not available when using drush 12.

```
$ ./vendor/bin/drush oe-paragraphs-update-banner-data:run         
                                                                             
  There are no commands defined in the "oe-paragraphs-update-banner-data" namespace.
```
The commands are being declared in:
- oe_paragraphs_carousel.services.yml
- oe_paragraphs_banner.services.yml

 ... but this is ignored.

In drush 12 the old way to declare the service in `drush.services.yml` still works and this would be a quick solution, also compatible with 11.

But this is going to be decprecated in version 13. There are other ways but I'm not sure they're compatible with drush 11.
https://github.com/drush-ops/drush/blob/12.x/docs/commands.md

Drush 12 is the [recommended version of drush for Drupal core 10](https://www.drupal.org/docs/upgrading-drupal/upgrading-from-drupal-8-or-later/how-to-upgrade-from-drupal-9-to-drupal-10#s-4-upgrade-to-drupal-10), so it should be fully supported by `oe_paragraphs` after 1.19, since it's D10 compatible.
I hope you can fix this, thanks.

**Comment by nagyad** [comment]
@dxvargas the drush.services.yml is not mandatory with Drush 12. [See this drupal issue.](https://www.drupal.org/project/eca/issues/3357771#comment-15040329)

Drush 12 commands should be defined with php attributes and moved under correct namespace. [See this article. ](https://www.velir.com/ideas/2023/06/29/drupalcon-2023-new-commands-in-drush-12-and-their-uses)
We will have to adapt these commands accordingly.
See this commit for a correct adaptation: https://github.com/openeuropa/oe_content/pull/609/commits/1e3c0de55614f5265e6e9e09c3151bc7d360c378

**Comment by nagyad** [comment]
Will be fixed by: https://github.com/openeuropa/oe_paragraphs/pull/219
