### ISSUE TITLE
Inpage navigation lost when paragraph "Edit mode" is set to "closed"

### ISSUE THREAD

**Issue by vever001** [openeuropa/oe_paragraphs#45]
The inpage navigation is lost when paragraph "Edit mode" is set to "closed".

Steps:
- As an example, I'm using the oe_demo_landing_page from oe_paragraphs_demo
- In "Manage form display", for the Body using "paragraphs with variants", set the "Edit mode" to "closed".
- Create a Demo landing page node with an inpage nav (e.g: 1 content row and 2 rich text inside)
- Save, the inpage nav is there (OK)
- Edit it and save immediately => the inpage nav is lost

**Comment by upchuk** [comment]
@vever001 

Hey there, thanks for reporting this. We recently discovered this as well and we fixed it in https://github.com/openeuropa/oe_paragraphs/pull/47.

Sorry for the late reply.
