### ISSUE TITLE
The "field_item:typed_link" plugin does not exist. Valid plugin IDs for Drupal\Core\TypedData\TypedDataManager are: entity_revision_reference,........

### ISSUE THREAD

**Issue by msnassar** [openeuropa/oe_paragraphs#84]
Error during updb:

>  [notice] Update started: oe_paragraphs_post_update_10002
The "field_item:typed_link" plugin does not exist. Valid plugin IDs for Drupal\Core\TypedData\TypedDataManager are: entity_revision_reference,........

It seems we needed to clear the cache after install the module 
https://github.com/openeuropa/oe_paragraphs/blob/master/oe_paragraphs.post_update.php#L93

Hint:
\Drupal\Core\TypedData\TypedDataManager::clearCachedDefinitions

**Comment by ademarco** [comment]
Thank you for reporting @msnassar, could you please open a PR with the fix?

**Comment by msnassar** [comment]
@ademarco Done...
